name: climate
channels:
- defaults
dependencies:
- _libgcc_mutex=0.1
- blas=1.0
- bokeh=2.3.1
- ca-certificates=2021.4.13
- certifi=2020.12.5
- click=7.1.2
- cloudpickle=1.6.0
- cycler=0.10.0
- cytoolz=0.11.0
- dask=2021.4.0
- dask-core=2021.4.0
- dbus=1.13.18
- distributed=2021.4.0
- expat=2.3.0
- flask=1.1.2
- fontconfig=2.13.1
- freetype=2.10.4
- fsspec=0.9.0
- glib=2.68.1
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- heapdict=1.0.1
- icu=58.2
- intel-openmp=2021.2.0
- itsdangerous=1.1.0
- jinja2=2.11.3
- jpeg=9b
- kiwisolver=1.3.1
- lcms2=2.12
- ld_impl_linux-64=2.33.1
- libffi=3.3
- libgcc-ng=9.1.0
- libgfortran-ng=7.3.0
- libpng=1.6.37
- libstdcxx-ng=9.1.0
- libtiff=4.1.0
- libuuid=1.0.3
- libxcb=1.14
- libxml2=2.9.10
- locket=0.2.1
- lz4-c=1.9.3
- markupsafe=1.1.1
- matplotlib=3.3.4
- matplotlib-base=3.3.4
- mkl=2021.2.0
- mkl-service=2.3.0
- mkl_fft=1.3.0
- mkl_random=1.2.1
- msgpack-python=1.0.2
- ncurses=6.2
- numpy=1.20.1
- numpy-base=1.20.1
- olefile=0.46
- openssl=1.1.1k
- packaging=20.9
- pandas=1.2.4
- partd=1.2.0
- pcre=8.44
- pillow=8.2.0
- pip=21.0.1
- psutil=5.8.0
- pyparsing=2.4.7
- pyqt=5.9.2
- python=3.9.4
- python-dateutil=2.8.1
- pytz=2021.1
- pyyaml=5.4.1
- qt=5.9.7
- readline=8.1
- scipy=1.6.2
- setuptools=52.0.0
- sip=4.19.13
- six=1.15.0
- sortedcontainers=2.3.0
- sqlite=3.35.4
- tblib=1.7.0
- tk=8.6.10
- toolz=0.11.1
- tornado=6.1
- typing_extensions=3.7.4.3
- tzdata=2020f
- werkzeug=1.0.1
- wheel=0.36.2
- xarray=0.17.0
- xz=5.2.5
- yaml=0.2.5
- zict=2.0.0
- zlib=1.2.11
- zstd=1.4.9

